// <auto-generated />
namespace SppApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update4));
        
        string IMigrationMetadata.Id
        {
            get { return "202009230956265_Update4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
